### PR TITLE
smaller fixes

### PR DESCRIPTION
**Pull request by tpokorra**
adding projector view for nomination stage again.
fix for location of logo in top bar for mobile phones.
fix for div on admin page.
small fix for running the PHPUnit tests.

I have now a test job, which I run manually: https://lbs.solidcharity.com/package/tpokorra/bof/test
The source of the setup and test script: https://github.com/tpokorra/lbs-bof/blob/master/test/setup.sh

@franc6 : thanks for reviewing!

### CODE REVIEW

**Comment by franc6** [comment]
In db2ad90, you added php-xdebug and php-pdo-sqlite to be installed by ansible.  But those are only needed for running the unit tests, which I don't think should be done on an installation; I don't think it would hurt anything, but I don't see how it helps, either. :)  And the additional components might not be desirable on some installations.  :)

Additionally, it should be "composer install --dev" to get the developer dependencies installed, not just "composer install".   :)

**Comment by tpokorra** [comment]
Thanks for the comments, I have fixed the issues I hope!

**Comment by franc6** [comment]
I'm not familiar enough with ansible.  :(

If I understand it correctly, php-pdo-sqlite and php-xdebug will still be installed when ansible installs apache (see ansible/roles/lamp/tasks/main.yml, lines 7 - 10)?

**Comment by tpokorra** [comment]
you are completely right...
I was doing multiple things at the same time, and forgot to delete the packages in that line you mentioned.

**Comment by franc6** [comment]
I really wish I could say I've never done something similar. :)

**Pull request merged**
