### PR TITLE
Fixed #66

### LINKED ISSUE #66: the algorithm should move BOFs with the same facilitator to different time slots

### PR DESCRIPTION
**Pull request by franc6**
This really needs far more testing, as I've only tested a simple case by resetting the leader for workshops "topic13" and "topic4" to be "user53", and ensuring we have 3 rounds and 4 rooms.

The new code attempts to look for conflicts after assigning everything, (note that a conflict doesn't count if there is more than one leader for a workshop).  It then attempts to switch a conflicting workshop with another (but never switching with something assigned to location_id 0 or the prep BOF).  It then tests for conflicts again.  If there are fewer conflicts, this change is commited to the DB, and the next conflict is addressed.  If there are the same or more conflicts, the change is rolled back, and it attempts to move a different workshop for the same conflict. This continues until all conflicts are resolved, or a maximum number of attempts has been reached.
One of the areas of testing that I haven't focused on, is what happens if the conflict is with something in location 0 (or the prep BOF) to begin with.  In that case, it might well attempt to switch something from location 0, which would be less than ideal.  Tweaking the queries might prevent such an occurrence.

### CODE REVIEW

**Comment by franc6** [comment]
Please do **not** merge this PR yet.

I really think this needs to be tested with more scenarios first, and I'd like to automate such testing.  The current testing framework appears to be only for testing the UI.  Is there a preferred framework for testing this code?  I'm not very familiar with testing frameworks for PHP with good ability to mock a DB with raw queries like the code contains, so I can't really suggest one without research first.  I'm happy to do such research, too, so if nobody else has a good suggestion, please let me know, and I'll try to submit some.

Also, I'm pretty sure the conflict resolution code should get its own method in the Results class.  I left it inside calculateResult() as further encouragement not to merge this PR yet. :)

**Comment by tpokorra** [comment]
I have heard of PHPUnit, but have not used it myself yet.

https://phpunit.de/ "PHPUnit is a programmer-oriented testing framework for PHP.
It is an instance of the xUnit architecture for unit testing frameworks."

Here is the documentation for working with mocks: https://phpunit.readthedocs.io/en/9.0/test-doubles.html

**Comment by franc6** [comment]
Quick update: I've used PHPUnit in the past, but I didn't know about DbUnit, which was a module for PHPUnit for testing raw SQL queries.  DbUnit has been deprecated and removed, in the past few years, though.  I've been working on using PHPUnit and DbUnit with an eye for how to remove DbUnit from the testing, too.  I expect this will take quite a while, still.  I might break the original calculateResults() method into multiple, smaller, methods to make it easier to test each piece of its functionality separately, too.  Faking the entire database tends to be painful (as in a 206-line monster of a helper function to generate data that will cause specific types of conflicts). :)  I'd like to have something that's actually readable with readable unit tests when I'm done. :)

**Comment by franc6** [comment]
OK, now it's ready for review.  Some additional notes:

1) You must modify the database such that the workshop table uses the InnoDB engine.  Otherwise, conflict resolution will fail pretty miserably for any but the simplest of situations.
2) I initially used the deprecated DbUnit and an old version of PHPUnit, but that involved writing a lot of complex XML files for initial data situations and expected data.  The new way uses the latest PHPUnit code and doesn't require any data files.
3) In order to ensure small units of testing (and be able to mock out the database calls so we can test major logic separately), I had to break Results.php into multiple classes.  The first new class, DBO handles all SQL statements for Results.php.  The second contains the logging code, in order to maintain a looser coupling between the new DBO object and logging facilities.
4) If there aren't enough workshops to fill out all the time/room slots, the conflict resolution logic won't consider the open time/room slots.  I figure that's not too big a deal, but harder to code for, so maybe a separate issue should be logged for that, and somebody who's better at writing SQL queries can fix it. :)

Finally, if you don't like the direction I've taken with breaking out the code, please let me know.  I can always fold the new classes back into the original.  We'd just lose the unit testing, as we'd be left with only a full integration test for it -- trying to build a full integration test is possible, but goes back to requiring large amounts of data files, or writing a lot of the code that looks a lot like Results.php to populate the database -- which kinda defeats the purpose of unit testing. :)  If you do like the direction, I can break out the SQL calls from other classes in a similar fashion, and start adding unit tests for them, too.

**Comment by tpokorra** [comment]
sorry, things have been busy, I will try to look at it in the next days...
Your comments sound definitely good to me!
I will just try to get it work on my instance, and then will merge it.

**Comment by tpokorra** [comment]
@franc6 I like the PHPUnit tests, and I like the clean up of code that you did.
If you like to proceed into that direction, go for it!

**Pull request merged**
